### PR TITLE
Allow painting and exporting textures in 8K resolution (8192x8192)

### LINKED ISSUE #186: Allow exporting higher texture resolutions (more than 4K)
Currently Material Maker allows to export textures with up to 4K resolution.
I wish 8K and 16K were also possible.
Is that doable? What do you think?

### PR DESCRIPTION
**Pull request by Calinou**
This requires a powerful GPU with at least 4 GB of VRAM (6+ GB highly recommended).

On a GeForce GTX 1080, it works successfully with most examples I tested. Of course, you'll have to be patient while 8K textures are generated and exported :slightly_smiling_face: 

This closes #186.

### CODE REVIEW

**Comment by RodZill4** [comment]
Hmm sounds cool. How's painting framerate at 8K?

**Comment by Calinou** [comment]
> How's painting framerate at 8K?

I didn't test painting yet, but I'll try that. I get a feeling it might be too slow to be usable, so I can probably remove the ability to paint in 8K.

**Comment by RodZill4** [comment]
> I didn't test painting yet, but I'll try that. I get a feeling it might be too slow to be usable, so I may have to remove the ability to paint in 8K.

Even if painting is near unusable, could be a good idea to keep it for procedural layers and lucky owners of ultra high end GPUs.

**Comment by RodZill4** [comment]
Seems painting is completely unusable at 8K. I removed this option for now...

**Pull request merged**
