### PR TITLE
New design GraphNode

### PR DESCRIPTION
**Pull request by Cold-0**
Dark
Default
Light
image

### CODE REVIEW

**Comment by Calinou** [comment]
Looks good!

What about using a blue outline for the selected node? This would make it stand out much more.

**Comment by Coldragon** [comment]
For the shadow in the selected one I used the color of the border of the unlected but yeah A blue (like the default godot one) could be more explicit

**Comment by RodZill4** [comment]
I agree, looks great, but selected nodes deserve more visibility.

**Comment by RodZill4** [comment]
Next release is too close (should happen as soon as Godot 3.2.2 is available) to merge this now. I'll integrate it for 0.93.

**Comment by Coldragon** [comment]
image

I added a blueish outline to be more clear.

**Comment by Cold-0** [comment]
I'm cleaning my github a bit, I guess I can close this and remove the fork since you revamped theme long time ago ?

**Pull request closed without merging**
