### PR TITLE
Add seven segment display node

### PR DESCRIPTION
**Pull request by williamchange**
This adds a seven segment display(0-9) node with variable weight(segment length/width), and optional bevel map input:

ssd_sample

### CODE REVIEW

**Comment by RodZill4** [comment]
Hmm maybe it should be in "Simple" category instead of "Pattern" (just like text).

**Comment by RodZill4** [comment]
@williamchange Any thoughts about this before I merge? Again, thanks for contributing this, it's great!

**Comment by williamchange** [comment]
Yeah, I think this should be good to go

**Comment by RodZill4** [comment]
I'm not sure I understand your last 4 commits. They seem to repeat [d7a809f](https://github.com/RodZill4/material-maker/pull/468/commits/d7a809f46d929e1268a31bcd564242081683e785) and [70d9a3b](https://github.com/RodZill4/material-maker/pull/468/commits/70d9a3b5a51e6c4800af6e68a3b1c5030f9b6ee5).

**Pull request merged**
