### PR TITLE
Add Japanese Glyphs node

### PR DESCRIPTION
**Pull request by williamchange**
This adds the "Japanese Glyphs" node, which currently supports the 46 base characters for both writing systems in Hiragana/Katakana (excluding the Dakuten/Handakuten variants - i.e. か/が は/ぽ):

jp_glyph_sample

**Hiragana Samples**:
hiragana_samples

**Katakana Samples**:
katakana_samples

### CODE REVIEW

**Comment by Zireael07** [comment]
Can this only produce real glyphs or could it be tweaked to produce 'fake' characters?

**Comment by williamchange** [comment]
> Can this only produce real glyphs or could it be tweaked to produce 'fake' characters?

Do you have an example what do you mean by 'fake' characters? Right now this only draw the the characters as it is.

**Comment by Zireael07** [comment]
https://www.shadertoy.com/view/Xtcczj (this is more for the kanji than katakana/hiragana, but I guess something similar could be used)

**Comment by williamchange** [comment]
> https://www.shadertoy.com/view/Xtcczj (this is more for the kanji than katakana/hiragana, but I guess something similar could be used)

Oh cool, though I guess this is closer to what the runes node (i.e. https://www.shadertoy.com/view/MsXSRn) is doing as this produces fixed glyphs.

**Pull request merged**
