### PR TITLE
New Icon/Logo and Loading Screen

### PR DESCRIPTION
**Pull request by Hopefullyidontgetbanned**
Hi, I like this project so i designed a new Icon/Logo for it and tried to implement it natively, i'm new to godot so excuse me for any errors i made

The Splash Screen is identical however i changed the loading screen to this:
Screenshot (1329)
and added a new icon for project browser and for compiled binaries
icon

### CODE REVIEW

**Comment by RodZill4** [comment]
I intended to replace the RodzLabs logo with something else in the loading screen, but not necessarily a logo (see Gimp, Blender... splash screens).
Not sure about the logo itself either. Any other idea ?

**Comment by Hopefullyidontgetbanned** [comment]
it depends i Could change it to have a mesh with a procedral material made in material maker with the  Logo and text next to it however that would take longer.

**Comment by RodZill4** [comment]
As an extra challenge, let's make it entirely in Material Maker. ;)

For example:
logo_albedo

**Comment by Jummit** [comment]
I'd like it clean. Something like this would look good imo:
bitmap

**Comment by Hopefullyidontgetbanned** [comment]
I could do something like that

**Comment by Calinou** [comment]
I'd also prefer a flat/mostly flat shape as it can be represented with a SVG if we need it. With a screenshot of a procedural material, we can't regenerate it in an higher resolution easily (and it might not scale down well).

**Comment by RodZill4** [comment]
Although regenerating materials in different resolutions with Material Maker is a piece of cake, I like @Jummit simple proposal. Maybe stick a Godot icon somewhere?

**Comment by Jummit** [comment]
Something like this?
start_screen

**Comment by RodZill4** [comment]
@Jummit Yes. Maybe the other logo ?
https://github.com/godotengine/godot/blob/master/editor/icons/Logo.svg

**Comment by RodZill4** [comment]
Just modified the loading screen to:
loading

**Pull request closed without merging**
