### PR TITLE
added random color output to color tiler node

### PR DESCRIPTION
**Pull request by Arnklit**
Added in the random color output by packing the tiler functions output into a mat4.

The color tiler does not have it's own page in the manual, only a mention in the Tiler page that there is a color version, so I did not make any changes to documentation.

### CODE REVIEW

**Comment by RodZill4** [comment]
Uh? Why use a mat4 instead of an output parameter?

**Comment by Arnklit** [comment]
Sorry I don't follow. I probably did it in a stupid way. I thought this would be the only way to get more that 4 channels of data back from the function. Otherwise the tiler logic would have to run twice right?

**Comment by Arnklit** [comment]
or can you just assign to a variable in main code while you are inside an instance function?

**Comment by RodZill4** [comment]
No, glsl functions accept output parameters. Just add one and pass a variable defined in the Code tab.

**Comment by Arnklit** [comment]
ohhhh. Wow that makes a lot of things easier. I'll give that a go.

**Comment by RodZill4** [comment]
Looking at the code, I believe there's still a problem. You can probably trigger it by blending 2 Tiler nodes.

All variables declared in the "Main code" tab must be unique (they are defined for each usage of each node). Prefixing their name with "$(name_uv)" should fix this.

**Comment by Arnklit** [comment]
Ah of course. Added that now. Thanks for taking the time to give me some feedback on this so I know for next time,

**Pull request merged**
