### PR TITLE
Replace ItemList with custom list in add_node_popup

### PR DESCRIPTION
**Pull request by bonbonmiel**
#219

### CODE REVIEW

**Comment by RodZill4** [comment]
Hmm I'm not sure I like the new behavior with the filter (the filter remains, but is not always applied when showing the popup).

**Comment by RodZill4** [comment]
Hmm @bonbonmiel, thanks for that contribution, I modified a few details and added quick connect for inputs. Please tell me if you like the result (or if you find bugs I'd have introduced) so I can merge this PR.

**Comment by bonbonmiel** [comment]
Hey,
 - The filter was purposely not filtering when quick-adding a node because the options have already been filtered though a compatibility pass (so I figured it was better not to automatically re-filter them through the current search).
Peek 2020-11-07 18-01

 - I'm personnally happy with the ui and the feature set but there was feedback in the issue too so maybe it could be polished a bit before merging (e.g. the filter behavior).
(also for the record, quick-connect for inputs closes #99.)

 - There is also a bug where custom nodes you just added do not show in the list before you restart the program but I guess this doesn't have anything to do with this popup.

 - Regarding paterial spray, I didn't use it seriously for now. I'll sure give feedback when I do!
image

**Comment by RodZill4** [comment]
Well, that's *Material* Spray, I just typed a bit too fast (and too far from the center of keys) when commiting.

**Pull request merged**
