### PR TITLE
changed bricks node to use center of brick for random color seed to f…

### PR DESCRIPTION
**Pull request by Arnklit**
The random ID's were being generated from the position of the bricks, but not their centers causing the unique colors not to tile correctly.

This should partially fix https://github.com/RodZill4/material-maker/issues/237.

### CODE REVIEW

**Comment by novemberist** [comment]
Any chance you could apply the same fix to the UV output? 

Bildschirmfoto vom 2021-03-07 06-02-20

**Comment by Arnklit** [comment]
Ah yeah I think I can easily fix that. I'll make a pull request for that a bit later today.

**Comment by Arnklit** [comment]
Hmm, I cannot reproduce this error. I'm not seeing these issues on the UV layout. I remember I checked this as well when I saw this bug. Basically my fix for the Random Color was to do the same as the unique ids in the UV layout does in the blue channel as they were already using the center of the brick. Could you try to send a file where you lock off the randomness on the bricks node when it creates the error and I'll see if I get the error on the same file.

**Comment by novemberist** [comment]
Sorry. I'm not sure if this was accidentally or deliberately fixed in the meantime, but with the latest version from master, I can no longer reproduce this issue.

**Pull request merged**
