### PR TITLE
Fixes issues where node preview does not toggle correctly

### LINKED ISSUE #481: Node previews don't auto-hide if already enabled when material was loaded
**Material Maker version:**
latest dev (https://github.com/RodZill4/material-maker/commit/4a6b82e3c719d603aa56e334ecfe74117e06f0de)

**OS/device including version:**
Windows 10 Pro x64
Version		21H2
OS build		19044.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Issue description:**
Nodes with a previewed output enabled will not toggle the previews visibility on mouse-over if the preview was already enabled when loading the material.

**Steps to reproduce:**
1. Enable a preview by right-clicking the output pin of a node.
2. Save the material.
3. Load the material.
4. Move the cursor over the node.

**Video:**

https://user-images.githubusercontent.com/10762433/178157390-35b4cde1-7fda-4600-9faf-51e4c4d03076.mp4

### PR DESCRIPTION
**Pull request by BlacRyu**
Fixes #481, #482,  and #483

I've tested this on various nodes, trying to make sure it would work cleanly with any type of parameter. This is my first contribution, so apologies if there are any conflicts with design or code style.

### CODE REVIEW

**Comment by RodZill4** [comment]
BTW, do you have this problem that when you create a new gradient cursor, it is shown in front of the preview?

**Comment by BlacRyu** [comment]
> This looks pretty good, but I really don't like the gradient editor part (looks too specific, this hints it might break if value edit controls are modified).
Yeah, ideally I was hoping Godot would have a signal indicating that a new node was added to the scene tree. Then I could just check for any new children down the tree in generic.gd rather than needing to manually put checks in the control script(s). Not sure of a clean way to future proof it without something generic like that though.

> BTW, do you have this problem that when you create a new gradient cursor, it is shown in front of the preview?
I didn't notice that, no. Thanks for fixing it. I must have always created the cursors before the preview in my testing.

**Comment by BlacRyu** [comment]
Actually it looks like the scene tree does emit [a signal](https://docs.godotengine.org/en/stable/classes/class_scenetree.html?highlight=node_added#class-scenetree-signal-node-added) when nodes are added, I'll see if I can use that here to make it connect new children in a clean generic way.

**Comment by RodZill4** [comment]
I don't think it's a good idea, the scene tree emits a signal *whenever* a node is added, I don't think we want all nodes to listen to that signal. But maybe I'm wrong...

**Comment by BlacRyu** [comment]
Yeah I'm not knowledgeable enough about the performance overhead of signals, so if that's a concern I can just leave it as it is.

**Comment by BlacRyu** [comment]
It looks like the signals we really want, `child_entered_tree` and `child_exited_tree` have been added to godot 4, but aren't available in 3.x (yet). It looks like they may be added in 3.5 though: https://github.com/godotengine/godot/pull/57541

**Comment by BlacRyu** [comment]
Yeah in the thread I posted above they talk about `node_added` having "a huge performance cost and is only really relevant for debugging / editor tools". When they talk about performance they may be talking more of real-time performance for things like games though which need the highest framerate possible. If you can add a few hundred nodes all with previews on and not chug it's probably fine.

**Comment by BlacRyu** [comment]
Btw, Github only auto-linked the first issue I mentioned in the PR and it looks like I can't link the others. If you could, link #482 and #483 as this pr will close them.

**Pull request merged**
