### PR TITLE
Add Colormap node

### PR DESCRIPTION
**Pull request by vreon**
This node is similar to Colorize, but instead of a gradient parameter,
it samples an RGBA input image ~along the top edge~.

node_filter_colormap_samples

### CODE REVIEW

**Comment by paulofalcao** [comment]
It would also be nice to add an input to choose the y value, the line chosen, instead of always using the top one, the input image could have a variation along the y axis

**Comment by vreon** [comment]
@paulofalcao How about this? I'll update the docs/screenshots if it looks good!

Screenshot_2021-11-13_13-29-36

```js
{"connections":[],"nodes":[{"name":"colormap","node_position":{"x":-80,"y":-40},"parameters":{"direction":0,"offset":0.5},"seed":0,"seed_locked":false,"shader_model":{"code":"","global":"","inputs":[{"default":"$uv.x","label":"","longdesc":"The input greyscale image","name":"input","shortdesc":"Input","type":"f"},{"default":"vec4(vec3($uv.x), 1.0)","label":"","longdesc":"The colormap image to use","name":"colormap","shortdesc":"Colormap","type":"rgba"}],"instance":"","longdesc":"Remaps a greyscale image using another image as a lookup (sampled horizontally)","name":"Colormap","outputs":[{"longdesc":"The remapped RGBA image","rgba":"$colormap($direction)","shortdesc":"Output","type":"rgba"}],"parameters":[{"default":1,"label":"","longdesc":"The direction in which to sample the colormap","name":"direction","shortdesc":"Direction","type":"enum","values":[{"name":"Horizontal","value":"vec2($input($uv), $offset)"},{"name":"Vertical","value":"vec2($offset, $input($uv))"}]},{"control":"None","default":0.5,"label":"","longdesc":"The position at which to sample the colormap","max":1,"min":0,"name":"offset","shortdesc":"Offset","step":0.01,"type":"float"}],"shortdesc":"Colormap"},"type":"shader"}]}
```

**Comment by vreon** [comment]
Okay, this is ready for review!

**Comment by paulofalcao** [comment]
@vreon looks good! :)

**Pull request merged**
