### PR TITLE
added AppImage [Linux]

### PR DESCRIPTION
**Pull request by stupid-kid-af**
AppImages can run on almost every linux distro.
So, I've made it.
Find the screenshot also

Screenshot_20220619_195908

### CODE REVIEW

**Comment by stupid-kid-af** [comment]
Here is the [source](https://github.com/stupid-kid-af/material-maker-AppImage)

**Comment by CocoR55** [comment]
Hello,
I use Appimage for different Linux Mint 20.3: Cinnamon, Mate, XFCE.
However only with XFCE, I get an issue.
I can move the windows right, left, up and down but they move very very slowly.
The processors don't have much activity in the 5% range. The RAM is not used much, about 10%.
If I don't start Appimage, no problem while I start Appimage whatever application, the problem occurs. I must kill Xorg to stop issue with all running applications....
Do you have any idea?
Regards,
CocoR55

**Comment by stupid-kid-af** [comment]
Any log?
If not then try to open this in live boot [Any distro with xfce]
Also give me some journalctl outputs.

**Comment by stupid-kid-af** [comment]
> Hello,
> I use Appimage for different Linux Mint 20.3: Cinnamon, Mate, XFCE.
> However only with XFCE, I get an issue.
> I can move the windows right, left, up and down but they move very very slowly.
> The processors don't have much activity in the 5% range. The RAM is not used much, about 10%.
> If I don't start Appimage, no problem while I start Appimage whatever application, the problem occurs. I must kill Xorg to stop issue with all running applications....
> Do you have any idea?
> Regards,
> CocoR55
> 

Also tell me your system's architecture.
Like my system has x86_64 architecture

**Comment by Calinou** [comment]
I wouldn't add a link to an AppImage built by a third-party to the official README. This has too many security implications, and it's best to stick to official Linux releases which already work on nearly all x86_64 Linux distributions.

**Comment by stupid-kid-af** [comment]
> I wouldn't add a link to an AppImage built by a third party to the official README. This has too many security implications, and it's best to stick to official Linux releases which already work on nearly all x86_64 Linux distributions.
> 
> In general, AppImage doesn't have much of a benefit for Godot. Godot is already built with all libraries statically linked, and official binaries are built on old enough Linux distributions to work almost everywhere.
> 
> If you want easier installation and automatic updates, [there's a Flatpak for it](https://flathub.org/apps/details/io.github.RodZill4.Material-Maker) :slightly_smiling_face: 

That's true
But still AppImages are better than flatpaks

**Comment by stupid-kid-af** [comment]
> I wouldn't add a link to an AppImage built by a third party to the official README. This has too many security implications, and it's best to stick to official Linux releases which already work on nearly all x86_64 Linux distributions.
> 
> In general, AppImage doesn't have much of a benefit for Godot. Godot is already built with all libraries statically linked, and official binaries are built on old enough Linux distributions to work almost everywhere.
> 
> If you want easier installation and automatic updates, [there's a Flatpak for it](https://flathub.org/apps/details/io.github.RodZill4.Material-Maker) slightly_smiling_face

Issue happens while opening the app on the loading page or splash screen. After loading and stuff it becomes normal.
This occurs in both AppImages and official binaries

**Comment by stupid-kid-af** [comment]
Also check here some videos of official_binaries and AppImage

https://user-images.githubusercontent.com/54206927/174494432-ed4be75d-0744-41a6-acb3-2ef47239ce07.mp4


https://user-images.githubusercontent.com/54206927/174494460-1d7344a0-f81a-4add-9a7a-1fb90f121c31.mp4

**Comment by stupid-kid-af** [comment]
Ignore this

**Comment by RodZill4** [comment]
For reasons stated by @Calinou

**Pull request closed without merging**
